name = "maralyrics"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "maralyrics-db"
database_id = "b27f5e8e-0b46-41df-8738-ddc611da58e3"

[vars]
ENVIRONMENT = "production"
